### ISSUE TITLE
Create user facing guide

### ISSUE THREAD

**Issue by scothis** [servicebinding/website#9]
The spec is focused (properly) on what implementations must and must not do. It's hard for a user trying to understand how they can leverage a `ServiceBinding` to do work within their cluster. We should create a user guide that gives a non-normative overview of the concepts and capabilities provided by the spec.

Topics to cover include:
- service and application references
   - using a label selector in the application reference
   - limiting which application containers are bound
- mapping custom values in the projected secret
- defining environment variables (and when not to)
- consuming a binding within an application
- cross-namespace services

**Comment by nebhale** [comment]
Closing in lieu of finer grained issues.
